import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
      appearance={{
        layout:{
          logoImageUrl: '/social.png',
          socialButtonsVariant: 'iconButton',
        },
        variables:{
          colorText: '#1c1f2e',
          colorPrimary: '#0E78F9',
          colorBackground: '#e5e7f1',
          colorInputBackground: '#8596e9',
          colorInputText: '#1c1f2e',
        }
      }}
      >
        {/* {`${inter.className} bg-dark-2 bg-dark-3`} */}
        <body className={`${inter.className}`}>
          {children}
          </body>
      </ClerkProvider>
    </html>
  );
}
